-- This schema is auto-generated by Spring JPA (spring.jpa.hibernate.ddl-auto=update)
-- Run this in Supabase SQL editor to pre-create tables if needed

CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created TIMESTAMPTZ DEFAULT NOW(),
    enabled BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS subreddits (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    created_date TIMESTAMPTZ DEFAULT NOW(),
    user_id BIGINT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS posts (
    id BIGSERIAL PRIMARY KEY,
    post_name VARCHAR(255) NOT NULL,
    url VARCHAR(255),
    description TEXT,
    vote_count INT DEFAULT 0,
    created_date TIMESTAMPTZ DEFAULT NOW(),
    subreddit_id BIGINT REFERENCES subreddits(id),
    user_id BIGINT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGSERIAL PRIMARY KEY,
    text TEXT NOT NULL,
    created_date TIMESTAMPTZ DEFAULT NOW(),
    post_id BIGINT REFERENCES posts(id),
    user_id BIGINT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS votes (
    id BIGSERIAL PRIMARY KEY,
    vote_type VARCHAR(10),
    post_id BIGINT REFERENCES posts(id),
    user_id BIGINT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS verification_tokens (
    id BIGSERIAL PRIMARY KEY,
    token VARCHAR(255),
    expiry_date TIMESTAMPTZ,
    user_id BIGINT REFERENCES users(id)
);
